/**
 * @fileoverview gRPC-Web generated client stub for proto.services.pingpong
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.21.12
// source: services/pingpong.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as services_pingpong_pb from '../services/pingpong_pb'; // proto import: "services/pingpong.proto"


export class PingPongServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetServerTime = new grpcWeb.MethodDescriptor(
    '/proto.services.pingpong.PingPongService/GetServerTime',
    grpcWeb.MethodType.UNARY,
    services_pingpong_pb.ClientTimeRequest,
    services_pingpong_pb.ServerTimeResponse,
    (request: services_pingpong_pb.ClientTimeRequest) => {
      return request.serializeBinary();
    },
    services_pingpong_pb.ServerTimeResponse.deserializeBinary
  );

  getServerTime(
    request: services_pingpong_pb.ClientTimeRequest,
    metadata?: grpcWeb.Metadata | null): Promise<services_pingpong_pb.ServerTimeResponse>;

  getServerTime(
    request: services_pingpong_pb.ClientTimeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: services_pingpong_pb.ServerTimeResponse) => void): grpcWeb.ClientReadableStream<services_pingpong_pb.ServerTimeResponse>;

  getServerTime(
    request: services_pingpong_pb.ClientTimeRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: services_pingpong_pb.ServerTimeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/proto.services.pingpong.PingPongService/GetServerTime',
        request,
        metadata || {},
        this.methodDescriptorGetServerTime,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/proto.services.pingpong.PingPongService/GetServerTime',
    request,
    metadata || {},
    this.methodDescriptorGetServerTime);
  }

  methodDescriptorPingStream = new grpcWeb.MethodDescriptor(
    '/proto.services.pingpong.PingPongService/PingStream',
    grpcWeb.MethodType.SERVER_STREAMING,
    services_pingpong_pb.PingRequest,
    services_pingpong_pb.PingMessage,
    (request: services_pingpong_pb.PingRequest) => {
      return request.serializeBinary();
    },
    services_pingpong_pb.PingMessage.deserializeBinary
  );

  pingStream(
    request: services_pingpong_pb.PingRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<services_pingpong_pb.PingMessage> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/proto.services.pingpong.PingPongService/PingStream',
      request,
      metadata || {},
      this.methodDescriptorPingStream);
  }

}

